steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    tag="$(if [ "$BRANCH_NAME" == "master" ]; then echo latest; else echo "$COMMIT_SHA"; fi)"
    docker build -t "gcr.io/$PROJECT_ID/rainforest-cli:$tag" .
images:
- 'gcr.io/$PROJECT_ID/rainforest-cli'
