#!/bin/sh

# Find incorrectly formatted files
unformatted=$(gofmt -l .)
[ -z "$unformatted" ] && exit 0

# If some files are not gofmt'd. Print message, list and fail.
echo >&2 "Go files must be formatted with gofmt. Please run:"
for fn in $unformatted; do
    echo >&2 "  gofmt -w $PWD/$fn"
done

exit 1
